#!/usr/bin/env bash
sudo pacman -S openssh ansible
sudo systemctl enable sshd
sudo systemctl start sshd


ansible-playbook  local.yml --become-password-file .become-password --vault-password-file .vault
