- name: Install core packages
  become: true
  community.general.pacman:
    name: [ "unzip",  "stow", "eza", "bat", "zoxide", "zsh", "curl", "rustup"]
    state: present

- name: Install build-essential
  become: true
  community.general.pacman:
    name: ["cmake", "gcc", "clang"]
  tags:
    - install
    - neovim
    - core

- name: Install productivity packages
  become: true
  community.general.pacman:
    name: [ "starship", "tmux", "fzf", "fd", "sd", "ripgrep", "docker", "jq", "k9s", "kubectl"]
    state: present

- name: Install docker
  become: true
  community.general.pacman:
    name: [ "docker"]
    state: present


- name: enable and start docker.service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: add the user to docker group
  user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes
