- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:vunguyentuan/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/dotfiles"
    recursive: no
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/dotfiles && stow --adopt .
  tags:
    - install
    - dotfiles
    - stow
